{"name": "Тест подтверждения отправки нового заказа с лендинга", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Н' is invalid: Введите корректную фамилию", "trace": "self = <test_order.TestOrder object at 0x7f11747e6150>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"dbb339fd-3700-4b06-8501-29133d20a1f3\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"dbb339fd-3700-4b06-8501-29133d20a1f3\")>\n\n    @allure.title('Тест подтверждения отправки нового заказа с лендинга')\n    @allure.description('Переходим к созданию нового заказа через кнопку в лендинге, \\\n                        заполняем необходимые поля и подтверждаем отправку заказа, \\\n                        проверяем, что заказ получил свой ID')\n    def test_order_from_landing_confirm(self, webdriver: WebDriver, wait: WebDriverWait):\n        self.__enter_order_from_landing(webdriver, wait)\n>       self.__fill_order_common(webdriver, wait)\n\ntests/test_order.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_order.py:101: in __fill_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7f117468ee50>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'Н' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Переходим к созданию нового заказа через кнопку в лендинге,                         заполняем необходимые поля и подтверждаем отправку заказа,                         проверяем, что заказ получил свой ID", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664691556, "stop": 1681664691888}, {"name": "Скролл к кнопке Заказать", "status": "passed", "start": 1681664691889, "stop": 1681664692091}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664692091, "stop": 1681664692500}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Лидия'"}], "start": 1681664692502, "stop": 1681664692583}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664692583, "stop": 1681664692790}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Никифорова'"}], "start": 1681664692790, "stop": 1681664692854}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Н' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "dd1e4ec8-fffa-4746-97c3-e145c4f2ae54-attachment.png", "type": "image/png"}], "start": 1681664692854, "stop": 1681664693179}], "start": 1681664691556, "stop": 1681664693180, "uuid": "ebf7fb3c-1e74-41e5-aac5-bb5172d673ce", "historyId": "420d983e753c6b4d76992404244a62dc", "testCaseId": "fa63f77e8914458d257dc77677e0a204", "fullName": "tests.test_order.TestOrder#test_order_from_landing_confirm", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181173-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}