{"name": "Тест неподтверждения отправки нового заказа с хэдера", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Н' is invalid: Введите корректную фамилию", "trace": "self = <test_order.TestOrder object at 0x7f11747e6850>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"7cc8d686-2da0-47c9-8c7d-f30165e14b6a\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"7cc8d686-2da0-47c9-8c7d-f30165e14b6a\")>\n\n    @allure.title('Тест неподтверждения отправки нового заказа с хэдера')\n    @allure.description('Переходим к созданию нового заказа через кнопку в хэдере, \\\n                        заполняем необходимые поля и **не** подтверждаем отправку заказа, \\\n                        проверяем, что вернулись на форму заполнения информации об аренде')\n    def test_order_from_header_not_confirm(self, webdriver: WebDriver, wait: WebDriverWait):\n        self.__enter_order_from_header(webdriver, wait)\n>       self.__fill_order_common(webdriver, wait)\n\ntests/test_order.py:56: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_order.py:101: in __fill_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7f11746f3cd0>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'Н' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Переходим к созданию нового заказа через кнопку в хэдере,                         заполняем необходимые поля и **не** подтверждаем отправку заказа,                         проверяем, что вернулись на форму заполнения информации об аренде", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664707611, "stop": 1681664708040}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664708040, "stop": 1681664708353}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Леонидовна'"}], "start": 1681664708353, "stop": 1681664708564}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664708564, "stop": 1681664708958}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Наина'"}], "start": 1681664708958, "stop": 1681664708994}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Н' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "cf2d620a-eefb-481e-a181-350c6b3d9fc2-attachment.png", "type": "image/png"}], "start": 1681664708994, "stop": 1681664709207}], "start": 1681664707611, "stop": 1681664709208, "uuid": "18ca3bde-cc2c-45c7-ac61-5db00e9c7147", "historyId": "8a77859421967105cb067b0359421618", "testCaseId": "87e587908bf5abd3b47ef7b9be612e24", "fullName": "tests.test_order.TestOrder#test_order_from_header_not_confirm", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181173-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}