{"name": "Тест получения статуса заказа с поля поиска в хэдере", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'З' is invalid: Введите корректную фамилию", "trace": "self = <test_track.TestTrack object at 0x7f240e121910>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"7d509f39-ecda-425d-8671-5b0187f49cab\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"7d509f39-ecda-425d-8671-5b0187f49cab\")>\n\n    @allure.title('Тест получения статуса заказа с поля поиска в хэдере')\n    @allure.description('Создаём заказ, кликаем на кнопку **Статус заказа**, вводим номер заказа \\\n                        кликаем на кнопку поиска заказа, проверяем, что на странице присутствует блок информации о заказе')\n    def test_get_order_status_from_header(self, webdriver: WebDriver, wait: WebDriverWait):\n        base_page = BasePage(webdriver, wait)\n    \n        base_page.click_button_accept_cookies()\n        base_page.click_button_order()\n    \n>       self.__make_order_common(webdriver, wait)\n\ntests/test_track.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_track.py:71: in __make_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7f240dfe3a10>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'З' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Создаём заказ, кликаем на кнопку **Статус заказа**, вводим номер заказа                         кликаем на кнопку поиска заказа, проверяем, что на странице присутствует блок информации о заказе", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664722738, "stop": 1681664723004}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664723004, "stop": 1681664723237}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Жанна'"}], "start": 1681664723240, "stop": 1681664723336}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664723336, "stop": 1681664723423}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Зуева'"}], "start": 1681664723423, "stop": 1681664723437}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'З' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "e2a41f7d-1d68-4bce-98ba-dd12785b32f1-attachment.png", "type": "image/png"}], "start": 1681664723437, "stop": 1681664723510}], "start": 1681664722737, "stop": 1681664723511, "uuid": "54ba7606-74e6-47f4-9cc6-cbb680c054ef", "historyId": "0ee7cc51b626bc9fba38ba15f466f3c4", "testCaseId": "e1aa41768f7d7fe6f2c39c4d88abc4ed", "fullName": "tests.test_track.TestTrack#test_get_order_status_from_header", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_track"}, {"name": "subSuite", "value": "TestTrack"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_track"}]}